name: Deploy Quizify-Backend

on: 
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t harshitalavania/quiz-portal-backend .
      - name: Publish Image to docker hub
        run: docker push harshitalavania/quiz-portal-backend:latest 

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull harshitalavania/quiz-portal-backend:latest
      - name: Create Docker Network if not exists
        run: |
          if ! sudo docker network ls | grep my_app_network; then
            sudo docker network create my_app_network
          fi
      - name: Delete old container
        run: sudo docker rm -f quizify-backend-container || true
      - name: Run Docker Container
        run: |
          sudo docker run -d \
          --name quizify-backend-container \
          --network my_app_network \
          -p 3000:3000 \
          -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
          harshitalavania/quiz-portal-backend
